[theme]
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
[server]
enableCORS = true
enableXsrfProtection = true
[browser]
gatherUsageStats = false
